//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab6.Account
{


    public partial class OpenAuthProviders
    {

        /// <résumé>
        /// Contrôle providersList.
        /// </résumé>
        /// <remarkques>
        /// Champ généré automatiquement.
        /// Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
        /// </remarques>
        protected global::System.Web.UI.WebControls.ListView providersList;

    }
}
